version: '3.1'

services:

  db:
    image: db_permission
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: permission
      TZ: "America/Mexico_City"
      PGTZ: "America/Mexico_City"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080    
